---
title: "Comparing MRMS and Tipping Buckets"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      fig.width = 12,
                      fig.height = 6)

library(tidyverse)
library(lubridate)
library(raster)
library(rgdal)
library(sf)
library(sp)
library(mapview)
library(terra)
library(tmap)
library(readr)
library(gridExtra)
library(ggplot2); theme_set(theme_bw(base_size = 16))
library(here)
library(irr)
library(plotly)
library(kableExtra)

```

```{r}
# #unzip all files, first list all files **ALREADY COMPLETE**
# zip <- list.files(path = 'E:/MRMS', pattern = '.gz',
#                   full.names = T)
# 
# #unzip all listed files
# test <- lapply(zip, gunzip)

# filename <- list.file(path = 'E:/MRMS', pattern = '.grib2')
# 
# #pull in an example raster
# r <- rast('E:/MRMS/RadarOnly_QPE_01H_00.00_20220716-000000.grib2') %>%
#   terra::project(., 'EPSG:26913')
#
# #bennett polygons
# ben <- vect('GIS/mulch_study_watersheds.shp') %>%
#   terra::project(., 'EPSG:26913')
#
# #cpf polygon
# cpf <- vect('GIS/cameron_boundary.shp') %>%
#   terra::project(., 'EPSG:26913')

# CODE BELOW IS OLD
# #crs(r) == crs(cpf)
#
# #crop raster to cpf
# crop <- terra::crop(r, ext(cpf))
#
# names(crop) <- 'p_mmhr'
#
# #only converting this to raster layer and SP  df for mapview
# #ben1 <- as(ben, "Spatial")
# #crop1 <- raster(crop)
#
# #mapview(ben1) + mapview(crop1)
#
# #extract using terra bc it has more functions :)
# extract <- terra::extract(crop, ben, fun = mean, touches = T, exact = T)
# extract$name <- ben$ID
#
# extract
# 
# filename <- 'RadarOnly_QPE_01H_00.00_20220716-000000.grib2'
# timestamp <- substr(filename, 25, 39)
# 
# extract <- extract %>%
#   mutate(datetime = ymd_hms(timestamp)) %>%
#   mutate(datetime = datetime - (6 * 60 * 60)) %>%
#   mutate(doy = yday(datetime)) %>%
#   mutate(hour = hour(datetime))
# 
# write.csv(extract, paste0('extract_', extract$doy[1],'_', extract$hour[1],'.csv'))

```

```{r make it a function}
# setwd('E:/MRMS_2022')
# 
# filenames <- list.files(".", pattern='.grib2', full.names=F)
# 
# #extract_MRMS <- function() {
#   
#   for(fileName in filenames) {
# 
# #pull in raster
# r <- rast(fileName) %>%
#   terra::project(., 'EPSG:26913')
#    
# #crop raster to cpf
# crop <- terra::crop(r, ext(cpf))
# 
# names(crop) <- 'p_mmhr'    
# 
# #extract using terra bc it has more functions :)
# extract <- terra::extract(crop, ben, fun = mean, touches = T, exact = T)
# extract$name <- ben$ID
#     
# timestamp <- substr(fileName, 25, 39)
# 
# extract <- extract %>%
#   mutate(datetime = ymd_hms(timestamp)) %>%
#   mutate(datetime = datetime - (6 * 60 * 60)) %>%
#   mutate(doy = yday(datetime)) %>%
#   mutate(hour = hour(datetime))
# 
# write.csv(extract, paste0('extract_', extract$doy[1],'_', extract$hour[1],'.csv'))
# 
#   }

```

```{r compile all CSVs}

#compile all CSVs
# mrms_21 <- list.files(path='./MRMS_data/2021', full.names = T) %>% 
#   lapply(read_csv) %>% 
#   bind_rows 
# 
# mrms_22 <- list.files(path='./MRMS_data/2022', full.names = T) %>% 
#   lapply(read_csv) %>% 
#   bind_rows 
# 
# #remove random columns
# mrms_21 <- mrms_21 %>%
#   dplyr::select(-c(doy, hour))
# 
# mrms_22 <- mrms_22 %>%
#   dplyr::select(-c(...1, ID, doy, hour))
# 
# write_csv(mrms_21, 'mrms_21.csv')
# write_csv(mrms_22, 'mrms_22.csv')

```

# Cumulative rainfall from TB vs MRMS

```{r get hourly tip bucket}

#bring in tb and sum as hourly
tip <- read_csv('bennett_rain_TB.csv') %>% 
  mutate(hour = hour(datetime),
         datetime = ymd_hm(datetime),
         date = as.Date(datetime)) %>%
  group_by(site, date, hour) %>%
  summarize(hr_p_mm = sum(precip_mm)) %>%
  mutate(datetime = ymd_h(paste(date, hour))) %>%
  filter(datetime > '2021-07-19 23:00') %>%
  ungroup() %>%
  dplyr::select(-c(date, hour)) %>%
  rename(p_mmhr = hr_p_mm) %>%
  mutate(source = 'tb')

#bring in mrms hourly  
mrms21 <- read_csv('mrms_21.csv') %>%
  dplyr::select(-c(...1, ID)) %>%
  rename(site = name) %>%
  mutate(site = tolower(site)) %>%
  mutate(datetime  = datetime - (2 * 60 * 60)) #should only be -1

mrms22 <- read_csv('mrms_22.csv') %>%
  rename(site = name) %>%
  mutate(site = tolower(site)) %>%
  mutate(datetime  = datetime - (2 * 60 * 60)) #should only be -1

mrms <- bind_rows(mrms21, mrms22) %>%
  mutate(source = 'mrms')

#bind together mrms and tb
all <- bind_rows(mrms, tip) %>%
  mutate(year = year(datetime)) %>%
  group_by(source, year, site) %>%
  mutate(cump = cumsum(p_mmhr)) %>%
  ungroup() %>%
  arrange(datetime)

# ggplotly to find events where there are MRMS and not TB
{all %>%
  filter(site == 'ue',
         year == 2022) %>%
  ggplot(aes(datetime, p_mmhr, color = source)) + 
  geom_line() +
  geom_point(size = 1.5) +
  labs(x = 'Date',
       y = 'p_mmhr')} %>%
  ggplotly()

#2021
all21 <- filter(all, year == 2021)

ggplot(all21, aes(datetime, cump, color = source)) + 
  geom_line() +
  facet_wrap(~site) +
  ggtitle('2021') +
  labs(x = 'Date',
       y = 'Cumulative summer rain (mm)')

#2022
all22 <- filter(all, year == 2022)

ggplot(all22, aes(datetime, cump, color = source)) + 
  geom_line() +
  facet_wrap(~site, scales = 'free')  +
  ggtitle('2022') +
  labs(x = 'Date',
       y = 'Cumulative summer rain (mm)')

```

# 1:1 for TB vs. MRMS

These data represent when the tipping bucket had a record.

```{r 1:1}
#compare the radar data when the TB has data
compare <- left_join(tip, mrms, by = c('datetime', 'site')) %>%
  mutate(year = year(datetime)) %>%
  rename(tb_rain_mm = p_mmhr.x,
         mrms_rain_mm = p_mmhr.y)

ggplot(compare, aes(tb_rain_mm, mrms_rain_mm)) + 
  geom_point() +
  geom_abline(intercept = 0, slope = 1, size=1, color='red') +
  facet_wrap(~site, scales = 'free') +
  ggtitle('1:1 TB vs MRMS when there are TB events')

#cum sum of when there is tb tips
compare <- compare %>%
  arrange(datetime) %>%
  group_by(year, site) %>% 
  mutate(cum_tb_mm = cumsum(tb_rain_mm),
         cum_mrms_mm = cumsum(replace_na(mrms_rain_mm, 0)))

ggplot(compare, aes(x=datetime)) + 
  geom_line(aes(y=cum_tb_mm, color ='TB')) +
  geom_line(aes(y=cum_mrms_mm, color = 'MRMS')) +
  scale_x_datetime(date_labels = '%b', breaks = '1 month') +
  scale_color_manual(name="Source", values=c('TB' = 'orange',
                                            'MRMS'="purple")) +
  facet_wrap(~site + year, scales = 'free') +
  ggtitle('Cumulative sums when TB has events')

# #shift tb then compare
# tip_shift <- tip %>%
#   mutate(datetime = datetime + (1*60*60)) #just testing a theory
# 
# #compare when there are tb events to MRMS with a 1hr tb shift
# compare_tbshift <- left_join(tip_shift, mrms, by = c('datetime', 'site')) %>%
#   mutate(year = year(datetime)) %>%
#   rename(tb_rain_mm = p_mmhr.x,
#          mrms_rain_mm = p_mmhr.y) %>% 
#   arrange(datetime) %>%
#   group_by(year, site) %>% 
#   mutate(cum_tb_mm = cumsum(tb_rain_mm),
#          cum_mrms_mm = cumsum(replace_na(mrms_rain_mm, 0)))
# 
# ggplot(compare_tbshift, aes(tb_rain_mm, mrms_rain_mm)) + 
#   geom_point() +
#   geom_abline(intercept = 0, slope = 1, size=1, color='red') +
#   facet_wrap(~site, scales = 'free') +
#   ggtitle('1:1 w/ TB shift')
# 
# ggplot(compare_tbshift, aes(x=datetime)) + 
#   geom_line(aes(y=cum_tb_mm, color ='TB')) +
#   geom_line(aes(y=cum_mrms_mm, color = 'MRMS')) +
#   scale_x_datetime(date_labels = '%b', breaks = '1 month') +
#   scale_color_manual(name="Source", values=c('TB' = 'orange',
#                                             'MRMS'="purple")) +
#   facet_wrap(~site + year, scales = 'free') +
#   ggtitle('Cumulative sum when TB has events w/ a 1 hr tb shift')


# compare_full <- right_join(tip, mrms, by = c('datetime', 'site'))
# 
# ggplot(compare_full, aes(p_mmhr.x, p_mmhr.y)) + 
#   geom_point() +
#   geom_abline(intercept = 0, slope = 1, size=1, color='red') +
#   facet_wrap(~site, scales = 'free') 

```

# Compare precip events

A comparison between TB and MRMS for a few rainfall events.

```{r event compares}
#use this df to pick out some events - but use all df to look actually compare
tb_event <- read_csv("tb_events.csv") %>%
  mutate(source = 'tb',
         year = year(endtime)) %>%
  rename(end_time = endtime)

# 2022-08-15 event
event1 <- all %>%
  filter(between(datetime, ymd_hms('2022-08-15 11:00:00'),
                 ymd_hms('2022-08-15 20:00:00'))) %>%
  filter(site == 'me') %>%
  group_by(source) %>%
  mutate(cum_rain_mm = cumsum(p_mmhr))
  
event1_line <- event1 %>%
ggplot(aes(datetime, p_mmhr, color = source, shape = source),
       size = 6) +
  geom_line() +
  ggtitle('ME event: 2022-08-15 11:00 to 20:00') +
  theme_bw() +
    theme(legend.position = "none") +
  labs(x = 'Time',
       y = 'Rain (mm/hr)')

event1_cum <- event1 %>%
ggplot(aes(datetime, cum_rain_mm, color = source, shape = source),
       size = 6) +
  geom_line() +
  ggtitle(' ') +
  theme_bw() +
  labs(x = 'Time',
       y = 'Cumulative rain (mm/hr)')

grid.arrange(event1_line, event1_cum, nrow = 1)

# 2022-07-15 event
event2 <- all %>%
  filter(between(datetime, ymd_hms('2022-07-15 15:00:00'),
                 ymd_hms('2022-07-16 01:00:00'))) %>%
  filter(site == 'ue') %>%
  group_by(source) %>%
  mutate(cum_rain_mm = cumsum(p_mmhr))
  
event2_line <- event2 %>%
ggplot(aes(datetime, p_mmhr, color = source, shape = source),
       size = 6) +
  geom_line() +
  ggtitle('UE event: 2022-07-15 16:00') +
  theme_bw() +
    theme(legend.position = "none") +
  labs(x = 'Time',
       y = 'Rain (mm/hr)')

event2_cum <- event2 %>%
ggplot(aes(datetime, cum_rain_mm, color = source, shape = source),
       size = 6) +
  geom_line() +
  ggtitle(' ') +
  theme_bw() +
  labs(x = 'Time',
       y = 'Cumulative rain (mm/hr)')

grid.arrange(event2_line, event2_cum, nrow = 1)

#event example 3
event3 <- all %>%
  filter(between(datetime, ymd_hms('2021-08-03 09:00:00'),
                 ymd_hms('2021-08-03 23:00:00'))) %>%
  filter(site == 'me') %>%
  group_by(source) %>%
  mutate(cum_rain_mm = cumsum(p_mmhr))
  
event3_line <- event3 %>%
ggplot(aes(datetime, p_mmhr, color = source, shape = source),
       size = 6) +
  geom_line() +
  ggtitle('ME event: 2021-08-03 9:00 to 23:00') +
  theme_bw() +
    theme(legend.position = "none") +
  labs(x = 'Time',
       y = 'Rain (mm/hr)')

event3_cum <- event3 %>%
ggplot(aes(datetime, cum_rain_mm, color = source, shape = source),
       size = 6) +
  geom_line() +
  ggtitle(' ') +
  theme_bw() +
  labs(x = 'Time',
       y = 'Cumulative rain (mm/hr)')

grid.arrange(event3_line, event3_cum, nrow = 1)

#event 4
event4 <- all %>%
  filter(between(datetime, ymd_hms('2021-08-03 09:00:00'),
                 ymd_hms('2021-08-03 20:00:00'))) %>%
  filter(site == 'uw') %>%
  group_by(source) %>%
  mutate(cum_rain_mm = cumsum(p_mmhr))
  
event4_line <- event4 %>%
ggplot(aes(datetime, p_mmhr, color = source, shape = source),
       size = 6) +
  geom_line() +
  ggtitle('UW event: 2021-08-03 09:00 to 20:00') +
  theme_bw() +
    theme(legend.position = "none") +
  labs(x = 'Time',
       y = 'Rain (mm/hr)')

event4_cum <- event4 %>%
ggplot(aes(datetime, cum_rain_mm, color = source, shape = source),
       size = 6) +
  geom_line() +
  ggtitle(' ') +
  theme_bw() +
  labs(x = 'Time',
       y = 'Cumulative rain (mm/hr)')

grid.arrange(event4_line, event4_cum, nrow = 1)


```

# MRMS spatial patterns for above example events

```{r spatial examples}
#bennett polygons - only bring in once
# ben <- vect('GIS/mulch_study_watersheds.shp') %>%
#    terra::project(., 'EPSG:26913')
# 
# ben1 <- as(ben, "Spatial")
#  
# #cpf polygon - only  bring in once
# cpf <- vect('GIS/cameron_boundary.shp') %>%
#    terra::project(., 'EPSG:26913')
# ##############################################
# #event 1 from above 
# #pull in an example raster -- add 7 hrs
# r <- rast('E:/MRMS_2022/RadarOnly_QPE_01H_00.00_20220816-030000.grib2') %>%
#   terra::project(., 'EPSG:26913')
# 
# #crop raster to cpf
# crop <- terra::crop(r, ext(cpf))
#  
# names(crop) <- 'p_mmhr'
# 
# #crop1 <- raster(crop) #only doing this for mapview purposes
# 
# #mapview(ben1) + mapview(crop1)
# 
# #extract using terra bc it has more functions :)
# extract1_20 <- terra::extract(crop, ben, touches = T, exact = T) %>%
#   filter(ID == 1) %>%
#   mutate(datetime = '2022-08-15 20:00')
# 
# extract1_11 <- extract1_11 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1_12 <- extract1_12 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1_13 <- extract1_13 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1_14 <- extract1_14 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1_15 <- extract1_15 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1_16 <- extract1_16 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1_17 <- extract1_17 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1_18 <- extract1_18 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1_19 <- extract1_19 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1_20 <- extract1_20 %>%
#   rename(site = ID) %>%
#   mutate(site = 'me',
#          source = paste0('mrms',1:5))
# 
# extract1 <- bind_rows(extract1_11, extract1_12,
#                       extract1_13,extract1_14,
#                       extract1_15,extract1_16,
#                       extract1_17,extract1_18,
#                       extract1_19,extract1_20) %>%
#   dplyr::select(-fraction) %>%
#   mutate(datetime = ymd_hm(datetime))

## notice this data does not include the shift that is ALREADY included above
load('event1_spatial.Rdata') 

event1_spatial %>%
ggplot(aes(datetime, p_mmhr, color = source, shape = source)) +
  geom_line(size = 0.75) +
  geom_point(size = 4) +
  ggtitle('ME event: 2022-08-15 11:00 to 20:00') +
  theme_bw() +
  labs(x = 'Time',
       y = 'Rain (mm/hr)') +
  scale_color_brewer(palette = "Dark2") +
  scale_x_datetime(breaks = '1 hour', date_labels = "%l %p")

#shift tb by an hour
event1_spatial_tbshift <- event1_spatial %>%
  mutate(datetime = if_else(source == 'tb', datetime + (1*60*60),
                          datetime)) #just testing a theory

event1_spatial_tbshift %>%
ggplot(aes(datetime, p_mmhr, color = source, shape = source)) +
  geom_line(size = 0.75) +
  geom_point(size = 4) +
  ggtitle('ME event: 2022-08-15 11:00 to 20:00 w/ TB shift') +
  theme_bw() +
  labs(x = 'Time',
       y = 'Rain (mm/hr)') +
  scale_color_brewer(palette = "Dark2") +
  scale_x_datetime(breaks = '1 hour', date_labels = "%l %p")

#######################################################################

#TIME FOR EVENT 2
#pull in an example raster -- add 7 hrs
# r <- rast('E:/MRMS_2022/RadarOnly_QPE_01H_00.00_20220716-080000.grib2') %>%
#   terra::project(., 'EPSG:26913')
# 
# #crop raster to cpf
# crop <- terra::crop(r, ext(cpf))
#  
# names(crop) <- 'p_mmhr'
# 
# #extract using terra bc it has more functions :)
# extract2_01 <- terra::extract(crop, ben, touches = T, exact = T) %>%
#   filter(ID == 4) %>%
#   mutate(datetime = '2022-07-16 01:00')
# 
# extract2_15 <- extract2_15 %>%
#   rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4))
# 
# extract2_16 <- extract2_16 %>%
#   rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4))
# 
# extract2_17 <- extract2_17 %>%
#   #rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4),
#          datetime = '2022-07-15 17:00') 
# 
# extract2_18 <- extract2_18 %>%
#   #rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4),
#          datetime = '2022-07-15 18:00') 
# 
# extract2_19 <- extract2_19 %>%
#   #rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4),
#          datetime = '2022-07-15 19:00') 
# 
# extract2_20 <- extract2_20 %>%
#   #rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4),
#          datetime = '2022-07-15 20:00') 
# 
# extract2_21 <- extract2_21 %>%
#   #rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4),
#          datetime = '2022-07-15 21:00') 
# 
# extract2_22 <- extract2_22 %>%
#   #rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4),
#          datetime = '2022-07-15 22:00') 
# 
# extract2_23 <- extract2_23 %>%
#   #rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4),
#          datetime = '2022-07-15 23:00') 
# 
# extract2_00 <- extract2_00 %>%
#   #rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4))
# 
# extract2_01 <- extract2_01 %>%
#   #rename(site = ID) %>%
#   mutate(site = 'ue',
#          source = paste0('mrms',1:4))
# 
# extract2 <- bind_rows(extract2_15, extract2_16,
#                       extract2_17,extract2_18,
#                       extract2_19,extract2_20,
#                       extract2_21,extract2_22,
#                       extract2_23,extract2_00,
#                       extract2_01) %>%
#   dplyr::select(-fraction) %>%
#   mutate(datetime = ymd_hm(datetime))

## notice this data does not include the shift that is ALREADY included above
load('event2_spatial.Rdata')

event2_spatial %>%
ggplot(aes(datetime, p_mmhr, color = source, shape = source)) +
  geom_line(size = 0.75) +
  geom_point(size = 4) +
  ggtitle('UE event: 2022-07-15 15:00 to 07-16 01:00') +
  theme_bw() +
  labs(x = 'Time',
       y = 'Rain (mm/hr)') +
  scale_color_brewer(palette = "Dark2") +
  scale_x_datetime(breaks = '1 hour', date_labels = "%l %p")

event2_spatial_tbshift <- event2_spatial %>%
  mutate(datetime = if_else(source == 'tb', datetime + (1*60*60),
                           datetime)) #just testing a theory
  
event2_spatial_tbshift %>%
ggplot(aes(datetime, p_mmhr, color = source, shape = source)) +
  geom_line(size = 0.75) +
  geom_point(size = 4) +
  ggtitle('UE event: 2022-07-15 15:00 to 07-16 01:00 w/ TB shift') +
  theme_bw() +
  labs(x = 'Time',
       y = 'Rain (mm/hr)') +
  scale_color_brewer(palette = "Dark2") +
  scale_x_datetime(breaks = '1 hour', date_labels = "%l %p")

```

# MRMS MI60

```{r mrms mi60}

load('rain_metrics.RData')

site_id <- c('me', 'mm', 'mw', 'ue', 'um', 'uw')

get_radar_intens <- function(site_id){
  
mrms_prep <- mrms %>%
  filter(site == site_id,
         p_mmhr > 0) %>%
  arrange(datetime) %>%
  mutate(site == paste0(site_id))
  
mrms_intens <- get_setup(mrms_prep, mrms_prep$datetime) %>%
  group_by(event, site) %>%
  summarize(MI60 = max(p_mmhr),
            P = sum(p_mmhr),
            event = mean(event),
             duration = max(datetime) - min(datetime),
             endtime = max(datetime),
            starttime = min(datetime)) %>%
  mutate(duration_hr = as.numeric(duration/60/60))

return(mrms_intens)

}

mrms_mi60 <- site_id %>%
  map(~ get_radar_intens(site_id = .)) %>%
  bind_rows() %>%
  mutate(year = year(endtime)) %>%
  filter(P > 1)

mrms_mi60 %>%
  filter(year == 2021) %>% 
ggplot(aes(endtime, MI60)) +
  geom_point() +
  facet_wrap(~site) +
  ggtitle('MRMS 2021')

mrms_mi60 %>%
  filter(year == 2022) %>% 
ggplot(aes(endtime, MI60)) +
  geom_point() +
  facet_wrap(~site) +
  ggtitle('MRMS 2022')

```

# Comparing tipping bucket to MRMS MI60s

```{r compare MI60s}
#read in tb events
# tb_mi60 <- read_csv("tb_events.csv") %>%
#   mutate(source = 'tb',
#          year = year(endtime)) %>%
#   rename(end_time = endtime) %>%
#   dplyr::select(MI60, end_time, Site, duration_hr, source, year) %>%
#   rename(site = Site)
# 
# mrms_mi60 <- mrms_mi60 %>%
#   mutate(source = 'mrms') %>%
#   ungroup() %>% 
#   dplyr::select(MI60, endtime, site, duration_hr, source, year) %>%
#   rename(end_time = endtime)
# 
# comp_mi60 <- bind_rows(tb_mi60, mrms_mi60)
# 
# comp_mi60 %>%
#   filter(year == 2021) %>% 
# ggplot(aes(end_time, MI60, color = source, shape = source)) +
#   geom_point() +
#   facet_wrap(~site) +
#   ggtitle('2021')
# 
# comp_mi60 %>%
#   filter(year == 2022) %>% 
# ggplot(aes(end_time, MI60, color = source, shape = source)) +
#   geom_point() +
#   facet_wrap(~site) +
#   ggtitle('2022')

```

# MRMS response

```{r MRMS stage response, echo = F}

#get all stage data
load('stage.Rdata')

#tweak stage response function
get_radar_stage_resp <- function(events_df, stage_df) {
  
  response <- data.frame()
  
  for(i in 1:nrow(events_df)){
    temp <- stage_df %>%
      filter(datetime >=(events_df$starttime[i]) 
             & datetime <=(events_df$endtime[i] + 12*60*60))
    
    temp$event = ifelse(temp$datetime >=(events_df$starttime[i]) 
                        & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                        events_df$event[i])
    
    temp$duration_hr = ifelse(temp$datetime >=(events_df$starttime[i]) 
                              & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                              events_df$duration_hr[i])
    
    temp$P = ifelse(temp$datetime >=(events_df$starttime[i]) 
                    & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                    events_df$P[i])
    
    temp$MI60 = ifelse(temp$datetime >=(events_df$starttime[i]) 
                       & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                       events_df$MI60[i])
    
    temp$starttime = ifelse(temp$datetime >=(events_df$starttime[i]) 
                            & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                            events_df$starttime[i])
    
    temp$endtime = ifelse(temp$datetime >=(events_df$starttime[i]) 
                          & temp$datetime <=(events_df$endtime[i] + 12*60*60),
                          events_df$endtime[i])
    
    response <- rbind(response, temp)
  }
  
  out <- response %>%
    group_by(event) %>%
    mutate(Stage_range = max(Stage_mm) - min(Stage_mm)) %>%
    group_by(event) %>%
    filter(Stage_mm == max(Stage_mm)) %>%
    rename(Stage_mm_max = Stage_mm) %>% 
    group_by(event) %>%
    filter(datetime == max(datetime)) %>%
    rename(datetime_maxstage = datetime) %>%
    mutate(starttime_rain = as_datetime(starttime),
           endtime_rain = as_datetime(endtime),
           lag2p_hr = as.numeric(datetime_maxstage - starttime_rain)) %>%
    filter(!duration_hr == 0) %>%
    mutate(response = ifelse(Stage_range > 2, 1, 0)) %>% 
    dplyr::select(-c(starttime, endtime))
  
}


#break out mimrs_mi60 by site
me_events <- mrms_mi60 %>%
  filter(site == 'me')

mm_events <- mrms_mi60 %>%
  filter(site == 'mm')

mw_events <- mrms_mi60 %>%
  filter(site == 'mw')

ue_events <- mrms_mi60 %>%
  filter(site == 'ue')

um_events <- mrms_mi60 %>%
  filter(site == 'um')

uw_events <- mrms_mi60 %>%
  filter(site == 'uw')

#now get stage response for each site
me_response <- get_radar_stage_resp(me_events, me_stage)
mm_response <- get_radar_stage_resp(mm_events, mm_stage)
mw_response <- get_radar_stage_resp(mw_events, mw_stage)
ue_response <- get_radar_stage_resp(ue_events, ue_stage)
um_response <- get_radar_stage_resp(um_events, um_stage) 
uw_response <- get_radar_stage_resp(uw_events, uw_stage)

mrms_response <- bind_rows(me_response, mm_response,
                           mw_response, ue_response,
                           um_response, uw_response)


ggplot(mrms_response, aes(site, Stage_range)) +
  geom_boxplot()

ggplot(mrms_response, aes(site, MI60)) +
  geom_boxplot()

#response summary
response_summary <- mrms_response %>%
  ungroup() %>% 
  dplyr::select(c(site, P, MI60,
                  Stage_mm_max, Stage_range, lag2p_hr, response)) %>%
  group_by(site) %>%
  summarize(Total_events = n(),
            Percent_response = (sum(response)/Total_events)*100,
            Max_P_mm = max(P),
            Mean_P_mm = mean(P),
            Max_MI60 = max(MI60),
            Mean_MI60 = mean(MI60),
            Max_Stage_Response_cm = max(Stage_range)/10,
            Mean_Stage_response_cm = mean(Stage_range)/10) %>%
  mutate_if(is.numeric,
            round,
            digits = 2)

kable(response_summary) %>%
  kable_styling()

#note, stage is mm 

```

# MRMS correlations

```{r cor}

# me correlations
me_cor <- me_response %>%
  ungroup() %>% 
  dplyr::select(duration_hr, P, MI60) %>%
  cor()

# mm correlations
mm_cor <- mm_response %>%
  ungroup() %>% 
  dplyr::select(duration_hr, P, MI60) %>%
  cor()
mm_cor

# mw correlations
mw_cor <- mw_response %>%
  ungroup() %>% 
  dplyr::select(duration_hr, P, MI60) %>%
  cor()

mw_cor

# ue correlations
ue_cor <- ue_response %>%
  ungroup() %>% 
  dplyr::select(duration_hr, P, MI60) %>%
  cor()
ue_cor

# um correlations
um_cor <- um_response %>%
  ungroup() %>% 
  dplyr::select(duration_hr, P, MI60) %>%
  cor()
um_cor

# uw correlations
uw_cor <- uw_response %>%
  ungroup() %>% 
  dplyr::select(duration_hr, P, MI60) %>%
  cor()
uw_cor

```

# MRMS logistic regressions

```{r}

ben_q <- read_csv('C:/Users/sears/Documents/Repos/CPF/bennett/larimerco_bennett_Q.csv') %>%
  rename(datetime = DateTime) %>%
  mutate(datetime = ymd_hm(datetime)) %>% 
  mutate(q_cms = q_cfs*0.028)

ben_q <- ben_q %>%
  rename(floor_dt = datetime)

#me 
me_response2 <- me_response %>%
  mutate(floor_dt = floor_date(datetime_maxstage, 'hour'))
    
me_response2 <- left_join(me_response2, ben_q, by = 'floor_dt') %>%
  mutate(doy = yday(floor_dt))

me_glm <- glm(response ~ q_cms + doy + duration_hr, data = me_response2, family = binomial)

me_response2$pred <- predict(me_glm, me_response2, type = 'response')

me_response3 <- me_response2 %>%
  mutate(prediction = if_else(pred > 0.5, 1, 0)) %>%
  ungroup() %>% 
  dplyr::select(response, prediction)

me_kappa <- kappa2(me_response3)
me_kappa$value

#mm
mm_response2 <- mm_response %>%
  mutate(floor_dt = floor_date(datetime_maxstage, 'hour'))
    
mm_response2 <- left_join(mm_response2, ben_q, by = 'floor_dt') %>%
  mutate(doy = yday(floor_dt))

mm_glm <- glm(response ~ q_cms + doy + duration_hr, data = mm_response2, family = binomial)

mm_response2$pred <- predict(mm_glm, mm_response2, type = 'response')

mm_response3 <- mm_response2 %>%
  mutate(prediction = if_else(pred > 0.5, 1, 0)) %>%
  ungroup() %>% 
  dplyr::select(response, prediction)

mm_kappa <- kappa2(mm_response3)
mm_kappa$value

#mw
mw_response2 <- mw_response %>%
  mutate(floor_dt = floor_date(datetime_maxstage, 'hour'))
    
mw_response2 <- left_join(mw_response2, ben_q, by = 'floor_dt') %>%
  mutate(doy = yday(floor_dt))

mw_glm <- glm(response ~ q_cms + doy + duration_hr, data = mw_response2, family = binomial)

mw_response2$pred <- predict(mw_glm, mw_response2, type = 'response')

mw_response3 <- mw_response2 %>%
  mutate(prediction = if_else(pred > 0.5, 1, 0)) %>%
  ungroup() %>% 
  dplyr::select(response, prediction)

mw_kappa <- kappa2(mw_response3)
mw_kappa$value

#ue
ue_response2 <- ue_response %>%
  mutate(floor_dt = floor_date(datetime_maxstage, 'hour'))
    
ue_response2 <- left_join(ue_response2, ben_q, by = 'floor_dt') %>%
  mutate(doy = yday(floor_dt))

ue_glm <- glm(response ~ q_cms + doy + duration_hr, data = ue_response2, family = binomial)

ue_response2$pred <- predict(ue_glm, ue_response2, type = 'response')

ue_response3 <- ue_response2 %>%
  mutate(prediction = if_else(pred > 0.5, 1, 0)) %>%
  ungroup() %>% 
  dplyr::select(response, prediction)

ue_kappa <- kappa2(ue_response3)
ue_kappa$value

#um
um_response2 <- um_response %>%
  mutate(floor_dt = floor_date(datetime_maxstage, 'hour'))
    
um_response2 <- left_join(um_response2, ben_q, by = 'floor_dt') %>%
  mutate(doy = yday(floor_dt))

um_glm <- glm(response ~ q_cms + doy + duration_hr, data = um_response2, family = binomial)

um_response2$pred <- predict(um_glm, um_response2, type = 'response')

um_response3 <- um_response2 %>%
  mutate(prediction = if_else(pred > 0.5, 1, 0)) %>%
  ungroup() %>% 
  dplyr::select(response, prediction)

um_kappa <- kappa2(um_response3)
um_kappa$value

#uw
uw_response2 <- uw_response %>%
  mutate(floor_dt = floor_date(datetime_maxstage, 'hour'))
    
uw_response2 <- left_join(uw_response2, ben_q, by = 'floor_dt') %>%
  mutate(doy = yday(floor_dt))

uw_glm <- glm(response ~ q_cms + doy + duration_hr, data = uw_response2, family = binomial)

uw_response2$pred <- predict(uw_glm, uw_response2, type = 'response')

uw_response3 <- uw_response2 %>%
  mutate(prediction = if_else(pred > 0.5, 1, 0)) %>%
  ungroup() %>% 
  dplyr::select(response, prediction)

uw_kappa <- kappa2(uw_response3)
uw_kappa$value

## make a df for this
first <- c('me', 'mm', 'mw',
           'ue', 'um', 'uw')
second <- c(me_kappa$value, mm_kappa$value, mw_kappa$value,
            ue_kappa$value, um_kappa$value, uw_kappa$value)

log_kappas <- data.frame(first,second) %>%
  rename(site = first,
         kappa = second)

kable(log_kappas) %>%
  kable_styling()



```

